apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlreef-deployment
spec:
  selector:
    matchLabels:
      app: ml-reef
  template:
    metadata:
      labels:
        app: ml-reef
    spec:
      containers:
      - name: mlreef
        image: registry.gitlab.com/mlreef/mlreef:latest
        volumeMounts:
          - name: mlreef-opt
            mountPath: /var/opt/gitlab
            subPath: gitlab
          - name: mlreef-etc
            mountPath: /etc/gitlab
            subPath: gitlab
          - name: mlreefdb-opt
            mountPath: /var/opt/mlreef
            subPath: mlreef
        ports:
        - containerPort: 80
          name: http-port
        - containerPort: 22
          name: ssh-port
        - containerPort: 8081
          name: mlreef-port
        - containerPort: 5050
          name: mlreef-port
        - containerPort: 10080
          name: mlreef-port
        - containerPort: 6000
          name: mlreef-port
        volumes:
          - name: mlreef-opt
            persistentVolumeClaim:
              claimName: mlreef-opt-pv-claim
          - name: mlreef-etc
            persistentVolumeClaim:
              claimName: mlreef-etc-pv-claim
          - name: mlreefdb-opt
            persistentVolumeClaim:
              claimName: mlreef-opt-db-claim
