apiVersion: v1
kind: PersistentVolume
metadata:
  name: mlreef-opt-db
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/opt/mlreef"
