apiVersion: v1
kind: PersistentVolume
metadata:
  name: mlreef-etc-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/etc/gitlab"
